#!/bin/bash

env | sort
echo "------------------------------------------------------------------------------ build begin"
echo "BASE_CONTAINER=$BASE_CONTAINER"
echo "DRIVER_MODULE=$DRIVER_MODULE"
echo "DOCKERFILE_PATH=$DOCKERFILE_PATH"
echo "IMAGE_NAME=$IMAGE_NAME"
echo "------------------------------------------------------------------------------"

docker build --build-arg BASE_CONTAINER=$BASE_CONTAINER --build-arg DRIVER_MODULE=$DRIVER_MODULE -f $DOCKERFILE_PATH -t $IMAGE_NAME .

echo "------------------------------------------------------------------------------"
echo "SOURCE_BRANCH=$SOURCE_BRANCH"
echo "SOURCE_COMMIT=$SOURCE_COMMIT"
echo "COMMIT_MSG=$COMMIT_MSG"
echo "DOCKER_REPO=$DOCKER_REPO"
echo "DOCKER_TAG=$DOCKER_TAG"
echo "------------------------------------------------------------------------------ build end"
